main: com.korsh.KorshPlugin
version: 1.0.0-SNAPSHOT
name: KorshPlugin
author: fanzi03
api-version: 1.21.11
commands: 
  calculate: 
    usage: /calculate <number> <operation> <number>
    description: Calculation
    aliases:
      - calc
  coordinates: 
    usage: /coordinates
    description: Get the player coordinates
    aliases:
      - coords
      - cds
  project:
    description: Components
    usage: /project 
  text_mod: 
    description: text moddification
    usage: /text_mod text
    aliases:
      - tm
  kit: 
    description: Getting the default kit
    usage: /kit
  check_item:
    description: checking the hidden info
    usage: /check_item


  
